version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8887:80"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=192.168.178.78
            - DB_PORT=3306
            - DB_DATABASE=speedtest
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - APP_TIMEZONE=UTC
            - QUEUE_CONNECTION=sync
